language: scala

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
  - mysql -e "ALTER DATABASE scalikejdbc CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" -usa -psa
  - bash -x ./travis_before.sh

script:
  - git add . --all
  - ./travis.sh

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

matrix:
  include:
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="mysql" TEST_SBT_VERSION="0.13.16"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="mysql" TEST_SBT_VERSION="1.1.0"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="postgresql" TEST_SBT_VERSION="1.1.0"
    - scala: scripted-test
      env: SCALIKEJDBC_DATABASE="h2" TEST_SBT_VERSION="1.1.0"
