language: scala

dist: xenial

services:
  - mysql

# The project supports OpenJDK 8+ / Oracle JDK 8,9,10
jdk:
  - openjdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
  - mysql -e "ALTER DATABASE scalikejdbc CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" -usa -psa
  - bash -x ./travis_before.sh

script:
  - git add . --all
  - sbt root213/test:compile

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
