language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1

jdk:
  - oraclejdk8

addons:
  postgresql: "9.4"

sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_script:
  - rm project/sbt-pgp.sbt
  - rm project/sbt-updates.sbt
  - psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
  - psql -c "CREATE DATABASE scalikejdbc;" -U postgres
  - mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
  - mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa

script:
  - bash -x ./travis_before.sh
  - git add . --all
  - travis_retry ./travis.sh
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"

matrix:
  include:
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="mysql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="postgresql"
    - scala: scripted-test
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.12.1
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="h2"
    - scala: 2.12.1
      jdk: oraclejdk8
      env: SCALIKEJDBC_DATABASE="hsqldb"
    - dist: trusty
      group: edge
      sudo: required
      scala: 2.12.1
      jdk: oraclejdk9
      env: SCALIKEJDBC_DATABASE="mysql"
      script:
      # https://github.com/sbt/sbt/pull/2951
      - git clone https://github.com/retronym/java9-rt-export
      - cd java9-rt-export/
      - git checkout 1019a2873d057dd7214f4135e84283695728395d
      - jdk_switcher use oraclejdk8
      - sbt package
      - jdk_switcher use oraclejdk9
      - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
      - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
      - cd ..
      - echo "sbt.version=0.13.14-RC1" > project/build.properties
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
      - bash -x ./travis_before.sh
      - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext ++$TRAVIS_SCALA_VERSION "project root211" test:compile testSequential
