name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 14
          - java: 15
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1.4.2
      with:
        java-version: "${{ matrix.java }}"
    - uses: coursier/cache-action@v4.1
    - name: install sbt
      run: curl -Ls https://git.io/sbt > ./sbt && chmod 0755 ./sbt
    - name: test
      run: ./sbt "core/testOnly scalikejdbc.jsr310.StatementExecutorSpec"
