name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 6 * * 3'
jobs:
  test:
    timeout-minutes: 50
    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: scalikejdbc
          MYSQL_USER: sa
          MYSQL_PASSWORD: sa
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: test
            db: mysql
            java: 8

    runs-on: ubuntu-latest
    steps:
    - name: setup database
      run: |
        while ! mysqladmin ping --user=root --password=root -h"127.0.0.1" ; do
          echo "await mysql start"
          sleep 1
        done
        if [[ "${{ matrix.db }}" == "mysql" ]]; then
          mysql -h 127.0.0.1 -e "GRANT ALL ON *.* TO sa@'%';FLUSH PRIVILEGES;" -uroot -proot
          mysql -h 127.0.0.1 -e "ALTER DATABASE scalikejdbc CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;" -uroot -proot
        fi
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java}}
        distribution: temurin
    - uses: coursier/cache-action@v6
      timeout-minutes: 5
    - name: copy jdbc settings
      run: |
        if [[ "${{ matrix.name }}" == "scripted" ]]; then
          cp scalikejdbc-mapper-generator/src/sbt-test/scalikejdbc-mapper-generator/${{ matrix.db }}.properties scalikejdbc-mapper-generator/src/sbt-test/scalikejdbc-mapper-generator/gen/test.properties &&
          cp scalikejdbc-mapper-generator/src/sbt-test/scalikejdbc-mapper-generator/${{ matrix.db }}.properties scalikejdbc-mapper-generator/src/sbt-test/scalikejdbc-mapper-generator/twenty-three/test.properties
        fi
        rm scalikejdbc-core/src/test/resources/jdbc.properties &&
        cp -p scalikejdbc-core/src/test/resources/jdbc_${{ matrix.db }}.properties scalikejdbc-core/src/test/resources/jdbc.properties
    - run: rm project/sbt-pgp.sbt
    - run: rm project/sbt-updates.sbt
    - if: ${{ matrix.db == 'mysql' }}
      run:
        # TODO flaky test
        echo 'ThisBuild / Test / testOptions += Tests.Exclude(Seq("somewhere.DatabasePublisherTckTest"))' > skip-mysql.sbt
    - run: |
        case ${{ matrix.name }} in
          "scala_3")
            sbt -v \
            "+ scalafmtCheckAll" \
            scalafmtSbtCheck \
            SetScala3 \
            root213/test \
            root213/publishLocal
            ;;
          "test")
            ./test.sh
            ;;
          "scripted")
            ./scripted.sh
            ;;
          *)
            echo "unknown job"
            exit 1
        esac
