name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 6 * * 3'
jobs:
  format:
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - run: |
        sbt "+ scalafmtAll" scalafmtSbt
        git diff --exit-code
    - if: ${{ (github.event_name == 'pull_request') && failure() }}
      run: |
        REVIEWDOG_VERSION="0.14.1"
        FILE_NAME="reviewdog_${REVIEWDOG_VERSION}_Linux_x86_64"
        wget -q https://github.com/reviewdog/reviewdog/releases/download/v${REVIEWDOG_VERSION}/${FILE_NAME}.tar.gz &&
        gunzip ${FILE_NAME}.tar.gz &&
        tar -xf ${FILE_NAME}.tar &&
        chmod +x ./reviewdog &&
        ./reviewdog -version
        export REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
        TMPFILE=$(mktemp)
        git diff > "${TMPFILE}"
        ./reviewdog \
          -name="scalafmt" \
          -f=diff \
          -f.diff.strip=1 \
          -reporter="github-pr-review" \
          -filter-mode="diff_context" \
          -fail-on-error="false" \
          -level="warning" <"${TMPFILE}"
